Repository Azure/azure-libraries-for-java, pull requests merged in 2018-03, with the labels that each got.

#250 [AutoPR containerinstance/resource-manager] Adding Container Exec Spec
  azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/ContainerExecRequestTerminalSize.java
  azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/ContainerExecRequestInner.java
  azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/ContainerExecResponseInner.java
  azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/ContainerGroupsInner.java
  azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/ContainerInstanceManagementClientImpl.java
  azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/implementation/StartContainersInner.java
Labels: RestPRMerged

#261 [AutoPR cognitiveservices/resource-manager] Remove advisor Java block from CognitiveServices readme.md
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/CheckSkuAvailabilityParameter.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/CheckSkuAvailabilityResult.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/Kind.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/MetricName.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/ProvisioningState.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/QuotaUsageStatus.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/SkuName.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/UnitType.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/Usage.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/implementation/AccountsInner.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/implementation/CheckSkuAvailabilitysInner.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/implementation/CognitiveServicesAccountCreateParametersInner.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/implementation/CognitiveServicesAccountInner.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/implementation/CognitiveServicesManagementClientImpl.java
  azure-mgmt-cognitiveservices/src/main/java/com/microsoft/azure/management/cognitiveservices/implementation/UsagesResultInner.java
Labels: RestPRMerged

#263 [AutoPR dns/resource-manager] Adding changes to support Private DNS Public Preview
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/CaaRecord.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/RecordType.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/SubResource.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/ZoneType.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/DnsManagementClientImpl.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/RecordSetInner.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/RecordSetsInner.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/ZoneInner.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/ZonesInner.java
Labels: RestPRMerged

#267 [AutoPR deviceprovisioningservices/resource-manager] Group DPSCertificate->List with other operations
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/AccessRightsDescription.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/AllocationPolicy.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/CertificateBodyDescription.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/CertificateProperties.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/CertificatePurpose.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/ErrorDetails.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/ErrorDetailsException.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/ErrorMesssage.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/IotDpsPropertiesDescription.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/IotDpsSku.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/IotDpsSkuInfo.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/IotHubDefinitionDescription.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/NameUnavailabilityReason.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/OperationDisplay.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/OperationInputs.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/State.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/TagsResource.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/VerificationCodeRequest.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/VerificationCodeResponseProperties.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/AsyncOperationResultInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/CertificateListDescriptionInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/CertificateResponseInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/DpsCertificatesInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/IotDpsClientImpl.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/IotDpsResourcesInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/IotDpsSkuDefinitionInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/NameAvailabilityInfoInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/OperationInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/OperationsInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/PageImpl.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/ProvisioningServiceDescriptionInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/SharedAccessSignatureAuthorizationRuleAccessRightsDescriptionInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/VerificationCodeResponseInner.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/implementation/package-info.java
  azure-mgmt-provisioningservices/src/main/java/com/microsoft/azure/management/provisioningservices/package-info.java
Labels: RestPRMerged

#280 [AutoPR keyvault/resource-manager] Add node config to keyvault for Swagger to SDK
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/KeyPermissions.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/StoragePermissions.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultPatchProperties.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultProperties.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/implementation/VaultsInner.java
Labels: RestPRMerged

#282 [AutoPR compute/resource-manager] Make OSDisk in storage profile for VMImages optional
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ImageStorageProfile.java
Labels: RestPRMerged

#285 [AutoPR dns/resource-manager] Fix SDK breaking change in 2017-10-01 DNS Swagger ref https://github.…
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/ZoneUpdate.java
  azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/implementation/ZonesInner.java
Labels: RestPRMerged

#278 [AutoPR postgresql/resource-manager] correct tier enum for postgres
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/GeoRedundantBackup.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/Operation.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/OperationDisplay.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/OperationOrigin.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/PerformanceTierServiceLevelObjectives.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/ProxyResource.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/ServerPropertiesForCreate.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/ServerPropertiesForDefaultCreate.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/ServerPropertiesForRestore.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/ServerState.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/ServerVersion.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/Sku.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/SkuTier.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/SslEnforcementEnum.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/StorageProfile.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/TrackedResource.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/CheckNameAvailabilitysInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/ConfigurationInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/ConfigurationsInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/DatabaseInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/DatabasesInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/FirewallRuleInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/FirewallRulesInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/LocationBasedPerformanceTiersInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/LogFileInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/LogFilesInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/NameAvailabilityInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/NameAvailabilityRequestInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/OperationListResultInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/OperationsInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/PageImpl.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/PerformanceTierPropertiesInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/PostgreSQLManagementClientImpl.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/ServerForCreateInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/ServerInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/ServerUpdateParametersInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/ServersInner.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/implementation/package-info.java
  azure-mgmt-postgresql/src/main/java/com/microsoft/azure/management/postgresql/package-info.java
Labels: RestPRMerged

#248 [AutoPR billing/resource-manager] [Billing RP] Rename BillingAccount->EnrollmentAccount.
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/BillingManagementClientImpl.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/BillingPeriodsInner.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/EnrollmentAccountListResultInner.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/EnrollmentAccountResultInner.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/EnrollmentAccountsInner.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/InvoicesInner.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/package-info.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/package-info.java
Labels: RestPRMerged

#253 [AutoPR managementgroups/resource-manager] Remove EntityViewParameter from Entities Call
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/ErrorDetails.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/ErrorResponse.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/ErrorResponseException.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/ManagementGroupChildInfo.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/ManagementGroupDetails.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/OperationDisplay.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/ParentGroupInfo.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/CreateManagementGroupRequestInner.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/ManagementGroupInfoInner.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/ManagementGroupInner.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/ManagementGroupSubscriptionsInner.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/ManagementGroupsAPIImpl.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/ManagementGroupsInner.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/OperationInner.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/OperationsInner.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/PageImpl.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/implementation/package-info.java
  azure-mgmt-managementgroups/src/main/java/com/microsoft/azure/management/managementgroups/package-info.java
Labels: RestPRMerged

#257 [AutoPR sql/resource-manager] Refactor sql readme.md
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/DatabaseEdition.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/ElasticPoolEdition.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/RestorePointType.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/TransparentDataEncryptionActivityStatus.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/TransparentDataEncryptionStatus.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/DatabaseInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/DatabaseOperationsInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/DatabaseUpdateInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ElasticPoolInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ElasticPoolOperationInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ElasticPoolOperationsInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ElasticPoolUpdateInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ImportRequestInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/ProxyResourceInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/RecommendedElasticPoolInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/RestorePointInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/RestorePointsInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlManagementClientImpl.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/TrackedResourceInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/TransparentDataEncryptionActivityInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/TransparentDataEncryptionInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/TransparentDataEncryptionsInner.java
Labels: RestPRMerged

#246 [AutoPR resources/resource-manager] Add more enum values for Identity/type in generic resource swagger
  azure-mgmt-locks/src/main/java/com/microsoft/azure/management/locks/implementation/ManagementLocksInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/HttpMessage.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/Plan.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/ResourceManagementErrorWithDetails.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PageImpl.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PolicyAssignmentInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PolicyAssignmentsInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PolicyClientImpl.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PolicyDefinitionInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PolicyDefinitionsInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceGroupExportResultInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceGroupInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceGroupsInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourceManagementClientImpl.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ResourcesInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/package-info.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/package-info.java
Labels: RestPRMerged

#291 [AutoPR monitor/resource-manager] [Monitor] Fixing incorrect specification of top parameter for Metrics API (#2655)
  azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/implementation/MetricsInner.java
  azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/package-info.java
Labels: RestPRMerged

#256 [AutoPR eventhub/resource-manager] [DO NOT MERGE UNTIL SERVICE TEAM DECIDES] Adding preview version of Event Hubs Cluster to Azure REST API specs.
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/MessagingRegionsProperties.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/ArmDisasterRecoveryInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/AuthorizationRuleInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/ConsumerGroupInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/EHNamespaceInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/EventHubManagementClientImpl.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/EventhubInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/MessagingPlanInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/MessagingPlansInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/MessagingRegionsInner.java
  azure-mgmt-eventhub/src/main/java/com/microsoft/azure/management/eventhub/implementation/RegionsInner.java
Labels: RestPRMerged

#283 [AutoPR] keyvault/resource-manager
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/KeyPermissions.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/StoragePermissions.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultPatchProperties.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/VaultProperties.java
  azure-mgmt-keyvault/src/main/java/com/microsoft/azure/management/keyvault/implementation/VaultsInner.java
Labels: ServicePR

#301 [AutoPR containerservices/resource-manager] [AKS] update list of supported VM sizes
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/ContainerServiceAgentPoolProfile.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/ContainerServiceMasterProfile.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/ContainerServiceVMSizeTypes.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/ContainerServiceClientImpl.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/ContainerServicesInner.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/ManagedClustersInner.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/implementation/package-info.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/package-info.java
Labels: RestPRMerged

#281 [AutoPR containerinstance/resource-manager] Fixing Error in Naming Convention for Rows and Cols in Terminal Size
  azure-mgmt-containerinstance/src/main/java/com/microsoft/azure/management/containerinstance/ContainerExecRequestTerminalSize.java
Labels: RestPRMerged

#272 Add versions config and plugin dependency
  pom.xml
  versionConfig.csv
Labels: RestPRInProgress

#304 [AutoPR resources/resource-manager] Move subscriptionId to global
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionClientImpl.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionsInner.java
Labels: RestPRMerged

#328 [AutoPR sql/resource-manager] Change databaseState in longTermRetention.json to longTermRetentionDatabaseState
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/LongTermRetentionDatabaseState.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/LongTermRetentionBackupsInner.java
Labels: RestPRMerged

#319 [AutoPR batchai/resource-manager] BatchAI. API spec 2018-03-01
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/AppInsightsReference.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/AzureBlobFileSystemReference.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/AzureFileShareReference.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/DataDisks.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/EnvironmentVariable.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/EnvironmentVariableWithSecretValue.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/FileServerReference.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/ImageReference.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/InputDirectory.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/JobPropertiesExecutionInfo.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/NodeSetup.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/OutputDirectory.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/PerformanceCountersSettings.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/PyTorchSettings.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/SetupTask.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/SshConfiguration.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/TensorFlowSettings.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/UnmanagedFileSystemReference.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/UsageName.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/BatchAIManagementClientImpl.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/FileInner.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/FileServerCreateParametersInner.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/JobCreateParametersInner.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/JobInner.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/JobsInner.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/JobsListOutputFilesOptionsInner.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/UsageInner.java
  azure-mgmt-batchai/src/main/java/com/microsoft/azure/management/batchai/implementation/UsagesInner.java
Labels: RestPRMerged

#332 [AutoPR billing/resource-manager] [Billing RP] Minor EnrollmentAccount API consistency tweaks
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/EnrollmentAccountInner.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/EnrollmentAccountListResultInner.java
  azure-mgmt-billing/src/main/java/com/microsoft/azure/management/billing/implementation/EnrollmentAccountsInner.java
Labels: RestPRMerged

#346 [AutoPR mysql/resource-manager] Fix swagger->sdk tag for go
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/GeoRedundantBackup.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/Operation.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/OperationDisplay.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/OperationOrigin.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/PerformanceTierServiceLevelObjectives.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/ProxyResource.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/ServerPropertiesForCreate.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/ServerPropertiesForDefaultCreate.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/ServerPropertiesForRestore.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/ServerState.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/ServerVersion.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/Sku.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/SkuTier.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/SslEnforcementEnum.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/StorageProfile.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/TrackedResource.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/CheckNameAvailabilitysInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/ConfigurationInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/ConfigurationsInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/DatabaseInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/DatabasesInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/FirewallRuleInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/FirewallRulesInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/LocationBasedPerformanceTiersInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/LogFileInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/LogFilesInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/MySQLManagementClientImpl.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/NameAvailabilityInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/NameAvailabilityRequestInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/OperationListResultInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/OperationsInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/PageImpl.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/PerformanceTierPropertiesInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/ServerForCreateInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/ServerInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/ServerUpdateParametersInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/ServersInner.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/implementation/package-info.java
  azure-mgmt-mysql/src/main/java/com/microsoft/azure/management/mysql/package-info.java
Labels: RestPRMerged

#336 [AutoPR cosmos-db/resource-manager] added descriptions to include Cosmos DB ARM template values
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/Capability.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/ConsistencyPolicy.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/DatabaseAccountConnectionString.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/DatabaseAccountKind.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/DefaultConsistencyLevel.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/FailoverPolicies.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/KeyKind.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/Location.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/MetricAvailability.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/MetricName.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/MetricValue.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/OperationDisplay.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/PercentileMetricValue.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/PrimaryAggregationType.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/UnitType.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/CollectionPartitionRegionsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/CollectionPartitionsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/CollectionRegionsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/CollectionsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/CosmosDBImpl.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabaseAccountCreateUpdateParametersInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabaseAccountInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabaseAccountListConnectionStringsResultInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabaseAccountListKeysResultInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabaseAccountPatchParametersInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabaseAccountRegionsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabaseAccountsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/DatabasesInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/MetricDefinitionInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/MetricInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/OperationInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/OperationsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PageImpl1.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PartitionKeyRangeIdRegionsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PartitionKeyRangeIdsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PartitionMetricInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PartitionUsageInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PercentileMetricInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PercentileSourceTargetsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PercentileTargetsInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/PercentilesInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/UsageInner.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/implementation/package-info.java
  azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb/package-info.java
Labels: RestPRMerged

#354 [AutoPR sql/resource-manager] [DO NOT MERGE] Adding InstanceFailoverGroups
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPoliciesInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPolicyInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/DatabaseOperationsInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlManagementClientImpl.java
Labels: RestPRMerged

#352 [AutoPR resources/resource-manager] Fix subscription paramter in SubscriptionClient
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionClientImpl.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/SubscriptionsInner.java
Labels: RestPRMerged

#355 [AutoPR sql/resource-manager] Removing instanceFailoverGroup from readme
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPoliciesInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/BackupLongTermRetentionPolicyInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/DatabaseOperationsInner.java
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlManagementClientImpl.java
Labels: RestPRMerged

#342 [AutoPR compute/resource-manager] added missing Swagger
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/AccessLevel.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/CreationData.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskCreateOption.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskCreateOptionTypes.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/DiskSku.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/HardwareProfile.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ImageStorageProfile.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/StorageAccountTypes.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/AvailabilitySetUpdateInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/AvailabilitySetsInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/ComputeManagementClientImpl.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/ComputeOperationValueInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/DisksInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/ImageUpdateInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/ImagesInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/OperationsInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/SnapshotInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/SnapshotsInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetVMInstanceViewInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetVMsInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetsInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineUpdateInner.java
  azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachinesInner.java
Labels: RestPRMerged

#361 [AutoPR containerservices/resource-manager] [AKS] specify byte format for base64-encoded kubeconfig
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/ContainerServiceAgentPoolProfile.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/ContainerServiceMasterProfile.java
  azure-mgmt-containerservice/src/main/java/com/microsoft/azure/management/containerservice/ContainerServiceVMSizeTypes.java
Labels: RestPRMerged

#362 [AutoPR sql/resource-manager] Sql job agent
  azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/LongTermRetentionBackupsInner.java
Labels: RestPRMerged

#311 [AutoPR resources/resource-manager] Fix some of the error in ARM swagger spec
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/DeploymentExtendedInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/PolicyDefinitionInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/TagDetailsInner.java
  azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/TagValueInner.java
Labels: RestPRMerged

#366 [AutoPR network/resource-manager] Fixed operationIds for non-CRUD operations in ExpressRouteCrossConnections
  azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ExpressRouteCrossConnectionPeeringsInner.java
  azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/ExpressRouteCrossConnectionsInner.java
  azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/NetworkManagementClientImpl.java
Labels: RestPRMerged
